### ISSUE TITLE
一部のサイトで文字化けを起こす

### ISSUE THREAD

**Issue by fu-sen** [CyberRex0/summaly-workers#1]
導入してみていましたが、一部のサイトの展開表示で文字化けの表示になってしまうのを確認しています。
おそらく Shift_JIS など UTF-8 でないサイトで発生しているのかな？と思いました。

**Comment by CyberRex0** [comment]
文字化けするのはおおむね仕様と言えます。
Workersでは文字エンコーディングを検出するライブラリが使えず、Content-Typeとmeta charsetを頼りにしています。
いずれも見つけられない場合、文字化けすることがあります。

**Comment by fu-sen** [comment]
いや、それが、summerflare では正常に表示されているのに、summaly-workers では文字化けを起こしているようで、
うまくその辺が処理できていない感じがしていたので、issues を建てていまして……

**Comment by CyberRex0** [comment]
ここを移植すればよさそうですね
https://github.com/misskey-dev/summerflare/blob/master/src/encoding.ts#L51-L69

**Comment by CyberRex0** [comment]
なかなか例となるサイトが見つからないため、文字化けが起きるサイトのURLを貼っていただけると助かります

**Comment by sunset0916** [comment]
下記サイトで文字化け確認しました。
https://shop.bird-electron.co.jp/
https://www.itmedia.co.jp/

**Comment by nagicat** [comment]
このサイトでも文字化けが確認できました。
https://www.goo-net.com/

**Comment by fu-sen** [comment]
有名どころでも文字化けありました。
https://www.itmedia.co.jp/

個人のページでは ISO-2022-JP（シフトではない「JIS」）のページでも文字化けが発生してたのも見てます。

**Comment by CyberRex0** [comment]
https://github.com/CyberRex0/summaly-workers/commit/907e2467cd59131440811d5a454194385b6580df で対応完了しました。情報提供ありがとうございました。

**Comment by fu-sen** [comment]
対応ありがとうございます。早速最新状態に更新して、タイムラインを確認していました。

> 有名どころでも文字化けありました。 https://www.itmedia.co.jp/

ちょうど関連記事が流れてきて、正常に表示されたのを確認できたところです。
どうやら文字化けなく良い感じに表示されてます。対応ありがとうございました。

これを見て更新する人へ: name の変更が入っているので、ご注意下さい。
https://github.com/CyberRex0/summaly-workers/commit/a5279469c91a5becec3245c0ac1a85b5ddfde51b
